apiVersion: v1
kind: ConfigMap
metadata:
  name: social-media-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: social_media
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONGODB_URI: mongodb://root:secret@mongodb:27017/notifications?authSource=admin
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  AUTHSERVICE_BASE_URL: http://authservice:8083
  USERSERVICE_BASE_URL: http://userservice:8081
  POSTSERVICE_BASE_URL: http://postservice:8082
  NOTIFICATIONSERVICE_BASE_URL: http://notificationservice:8084
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
  TRACING_SAMPLING_PROBABILITY: "1.0"
