apiVersion: v1
kind: Secret
metadata:
  name: social-media-secrets
type: Opaque
stringData:
  POSTGRES_USER: social
  POSTGRES_PASSWORD: social
  JWT_SECRET: change-this-secret-to-at-least-32-characters
  GATEWAY_INTERNAL_SIGNING_SECRET: change-this-internal-secret-to-at-least-32-characters
